services:
  kisa-app:
    container_name: kisa-app
    build: .
    environment:
      DATABASE_URL: "host=localhost user=postgres password=postgres dbname=kisa_db sslmode=disable"
    ports:
      - 8000:8000
    depends_on:
      kisa-db:
        condition: service_healthy
    links:
      - kisa-db
  kisa-db:
    container_name: kisa-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kisa_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: {}