services:
  kisa-app:
    container_name: kisa-app
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: ./kisa --http-mode
    depends_on:
      kisa-db:
        condition: service_healthy
      kisa-redis:
        condition: service_healthy
    links:
      - kisa-db
      - kisa-redis

  kisa-db:
    container_name: kisa-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kisa_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kisa-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: { }
  redis-data: { }