[app]

[http]
port = 8080

[database]
host = "kisa-db"
port = 5432
user = "postgres"
password = "postgres"
name = "kisa_db"
ssl = "disable"
timezone = "Europe/Istanbul"

[redis]
host = "kisa-redis"
port = 6379
password = "redis_password"
# Cache duration in seconds
cache = 60